### ISSUE TITLE
what about gta4 mesh+skel

### ISSUE THREAD

**Issue by Tosyk** [LendoK/Blender_GTA_V_model_importer#2]
Hi!
thanks for great script! can you make it work with gta4 files?
[ig_dwayne.zip](https://github.com/LendoK/Blender_GTA_V_model_importer/files/4525616/ig_dwayne.zip)

I have this error when tried to load gta4 characters:
`Traceback (most recent call last):
  File "C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_mesh_gta5\__init__.py", line 70, in execute
    return import_mesh.load(self, context, **keywords)
  File "C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_mesh_gta5\import_mesh.py", line 431, in load
    mod.object = skel
AttributeError: 'NoneType' object has no attribute 'object'

location: <unknown location>:-1

`

**Comment by LendoK** [comment]
Request accepted. Do you know if GTA 4 Models all have the same vertex structure, like in your example?

**Comment by Tosyk** [comment]
Thank you for respond! Since I’m not a programmer I can’t answer your question. But I can provide more samples!

**Comment by BrynnaDaRosa** [comment]
Sorry about the thread necro, but I was thinking about this, since IV is officially the only GTA game without a single blender tool, with the exception of that one plugin that only import paths for blender 2.79. If you found the time to add support or if we got some collaborators, this could be incredibly valuable to the IV modding community when all we have is GIMS IV which has been unsupported for years now, the only version of max where all of its features are working is Max 2012 which is close to impossible to get a hold of now.

Here are the differences in the V and IV open formats that i've been able to observe. 

Here's a V model, ig_sol
![image](https://user-images.githubusercontent.com/73003230/151894062-354b991b-7158-4fe7-93c9-918b4e7ad91c.png)

Here's an IV model, ig_derrick_mc
![image](https://user-images.githubusercontent.com/73003230/151894127-91cc3f85-abf7-4d33-88b7-9b7e51711e9d.png)

There are no odr's for each drawable, only meshes, not in folders. If you don't have IV, here's the model.
[ig_derrick_mc odd.zip](https://github.com/LendoK/Blender_GTA_V_model_importer/files/7975026/ig_derrick_mc.odd.zip)

What's weird is that my import error is different from Tosyk's:

```
Traceback (most recent call last):
  File "C:\Users\Niko\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Blender_GTA_V_model_importer-master\__init__.py", line 118, in execute
    return importer.load(self, context, **keywords)
  File "C:\Users\Niko\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Blender_GTA_V_model_importer-master\importer.py", line 443, in load
    meshObjects = loadODD(filepath, import_armature, **kwargs)
  File "C:\Users\Niko\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Blender_GTA_V_model_importer-master\importer.py", line 413, in loadODD
    loadSkeleton(kwargs["odd_skeleton_path"], **kwargs)
  File "C:\Users\Niko\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Blender_GTA_V_model_importer-master\importer.py", line 347, in loadSkeleton
    skeleton = buildArmature(skel_file)
  File "C:\Users\Niko\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\Blender_GTA_V_model_importer-master\importer.py", line 310, in buildArmature
    numBones = skel_file.data["members"][0]["NumBones"]
KeyError: 'NumBones'

location: <unknown location>:-1
```
