### ISSUE TITLE
TypeError when trying to import .odr into Blender

### ISSUE THREAD

**Issue by ViolentMinds** [LendoK/Blender_GTA_V_model_importer#23]
`Traceback (most recent call last):
  File "C:\Users\NZXT\Desktop\gtav shells\blender-2.82a-windows64\2.82\scripts\addons\Blender_GTA_V_model_importer-master\__init__.py", line 118, in execute
    return importer.load(self, context, **keywords)
  File "C:\Users\NZXT\Desktop\gtav shells\blender-2.82a-windows64\2.82\scripts\addons\Blender_GTA_V_model_importer-master\importer.py", line 451, in load
    meshObjects = [loadODR(filepath, import_armature, **kwargs)]
  File "C:\Users\NZXT\Desktop\gtav shells\blender-2.82a-windows64\2.82\scripts\addons\Blender_GTA_V_model_importer-master\importer.py", line 406, in loadODR
    return importMesh(mesh_path, shaders, import_armature, **kwargs)
  File "C:\Users\NZXT\Desktop\gtav shells\blender-2.82a-windows64\2.82\scripts\addons\Blender_GTA_V_model_importer-master\importer.py", line 246, in importMesh
    for num, geometry in enumerate(p.data["members"][0]["members"][1]["members"]):
TypeError: list indices must be integers or slices, not str

location: <unknown location>:-1

`

Blender 2.82
This was my last hope too because i cant import into 3ds max using openformats i/o because it says the odr is not supported version lol wish they would update that importer

gims was updated at least but with no way to import .odr im trying blender but now i have this error

**Comment by BrynnaDaRosa** [comment]
This plugin is only an importer. I would suggest abandoning openformats with how long GIMS has been abandoned. Look into the Sollumz plugin which works hand in hand with Codewalker's XML formats. (and Blender 3.0 for that matter)

**Comment by ViolentMinds** [comment]
Thank you I will look into those!
